name: Check style

on:
  push:
  pull_request:
  merge_group:

jobs:
  check-style:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Prepare
      run: |
        sudo apt-get update -y
        sudo apt-get install -y pkg-config cmake cmake build-essential shellcheck
        wget https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-2da3e7b/clang-format-20_linux-amd64
        echo "aa033826df57bd965486c291f2218531ecd38ed815e42dc186a938af564600cb26bc911c091faeb63d2ba981e3b85beddce36ad5d1837ffe83c7a417c13fd69e  clang-format-20_linux-amd64" | sha512sum -c
        mkdir -p ~/.local/bin
        mv clang-format-20_linux-amd64 ~/.local/bin/clang-format
        chmod +x ~/.local/bin/clang-format
    - name: Check fix_style
      run: scripts/fix_style.sh --dry-run
    - name: Check raw C types
      run: scripts/check_types.sh
    - name: Check raw stdlib includes
      run: scripts/check_standard_headers.sh
    - name: Check extern C annotation
      run: scripts/check_public_headers.sh
